#### Numpy创建数组
##### 1、使用np.array(list,dtype='数据类型')传入列表创建，数据类型可以省略
##### 2、使用np.arange(a,b,c)创建一维数组，a：开始 b：结束 c：步长
##### 3、使用np.zeros/ones((n,m))创建n行m列的数组，数组元素全�?0/1
##### 4、使用np.full((n,m),k)创建n行m列数组元素全为k

In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.arange(1,10,2)
c=np.zeros((3,3))
d=np.full((3,3),4)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 数组的属性
##### a.ndim:数组a的维度
##### a.shape:数组a的形状